---
sudo: false
dist: xenial
language: node_js
branches:
  only:
    - master
    - develop
node_js:
  - node
  - 'lts/*'
addons:
  firefox: 'latest'
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
    - "$HOME/.npm"
