---
sudo: false
dist: xenial
language: node_js
branches:
  only:
    - master
    - develop
node_js:
  - node

stages:
  - check
  - test
  - cov

jobs:
  include:
    - stage: check
      script:
        - npx aegir dep-check
        - npx nyc -s aegir test -t node && npx nyc report
        # - npm run lint

    - stage: test
      name: node
      script: npx aegir test -t node
    
    - stage: test
      name: chrome
      addons:
        chrome: stable
      script: npx aegir test -t browser -t webworker

    - stage: test
      name: firefox
      addons:
        firefox: latest
      script: npx aegir test -t browser -t webworker -- --browsers FirefoxHeadless
    
cache: npm
